In [2]:
import numpy as np

In [15]:
# making array from list
list = [1]
arr = np.array(list) # np.array creates an array
print(arr)

[1]


In [16]:
print(arr.ndim)

1


In [7]:
# 2 D array 
list1 = [1, 2, 3]
list2 = [4,5,6]
list_merge = np.array([list1, list2])
print(list_merge)

[[1 2 3]
 [4 5 6]]


In [8]:
print(list_merge.ndim) # ndim used to fund the dimention of array

2


In [14]:
# 3D array
list1 = [23, 54, 32]
list2 = [21, 43, 12]
list3 = [13, 24, 37]

merged_list = np.array([[list1, list2, list3]]) #no. of [] brackets decide the dimension of array
print(merged_list)
print(merged_list.ndim)

[[[23 54 32]
  [21 43 12]
  [13 24 37]]]
3


In [ ]:
# array attributes

In [21]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.shape) #for the shape of an array
print(arr.size) #for the size of an array
print(arr.dtype) #for the data type of an array
print(arr.ndim) #for dimension of an array

[[1 2 3]
 [4 5 6]]
(2, 3)
6
int64
2


In [22]:
# Types of array

In [26]:
#zero array
arr_zero = np.zeros((2, 3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [28]:
# one value array
arr_one = np.ones((3,4))
print(arr_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
#indentity metrix
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
#full array with specific value
arr_full = np.full((3,2), 7)
print(arr_full)

[[7 7]
 [7 7]
 [7 7]]


In [30]:
#methods in array

In [31]:
#arange method

arr_range = np.arange(1, 10, 2) #arange(start, stop, step)
print(arr_range)

[1 3 5 7 9]


In [32]:
# linspace method : for the specific no. of elements
arr_specific = np.linspace(1,10, 8)
print(arr_specific)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [33]:
#random method

In [37]:
#for the random value - float
print(np.random.rand(3,3))

[[0.18542025 0.41353788 0.10673679]
 [0.54992354 0.42736556 0.4789848 ]
 [0.8623583  0.37218179 0.28391254]]


In [38]:
# for the random value - integer
print(np.random.randint(1, 100, (3,3)))

[[95 56 89]
 [ 4 28 49]
 [68 39 44]]


In [40]:
# Array indexing and slicing

In [43]:
# for the 2D array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [53]:
#for the 3D array
arr_3D = np.array([[1,2,3], [4,5,6]])
print(arr_3D)


[[1 2 3]
 [4 5 6]]


In [57]:
print(arr_3D[1]) #this will return 1D array
print(arr_3D[1: ]) #this will return 2D array

[4 5 6]
[[4 5 6]]


In [60]:
print(arr_3D[0][0]) #for the specific element in array
print(arr_3D[:, 0]) #after : it is column and first is row
print(arr_3D[:, 2]) # output column 3 

1
[1 4]
[3 6]


In [62]:
arr3 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
print(arr3[::, 1]) #3D array indexing and slicing
print(arr3[1::, 1]) #3D array column slicing
print(arr3[::2, 1:2]) #3D array row and column slicing

[2 5 8]
[5 8]
[[2]
 [8]]


In [69]:
#Array Reshaping and flattening

In [76]:
arr_r = np.array([1,2,3,4,5,6])
reshaped = arr_r.reshape(6,1)
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [77]:
reshape = arr_r.reshape(2,3)
print(reshape)

[[1 2 3]
 [4 5 6]]


In [78]:
#flatten function - used to change the 2D array to 1D array
print(arr_r.flatten())

[1 2 3 4 5 6]


In [79]:
#Array stacking and splitting

In [86]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([a,b])
hstack = np.hstack([a,b])
print(stack)

[1 2 3 4 5 6]


In [87]:
#vertical stack
vstack = np.vstack([a,b])
print(vstack)

[[1 2 3]
 [4 5 6]]


In [90]:
#splitting horizontal and vertical
hsplit = np.hsplit(c, 3)

for s in hsplit:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [92]:
#vertical split
vsplit = np.vsplit(c, 2)

for s in vsplit:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [93]:
#Mathematical operation on array

In [94]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [95]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [97]:
angle = np.array([30, 45, 90])
print(np.sin(angle))
print(np.cos(angle))

[-0.98803162  0.85090352  0.89399666]
[ 0.15425145  0.52532199 -0.44807362]


In [99]:
c = np.array([a, b])
print(c)
print(c.T) #transpose of matrix

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [100]:
print(np.dot(a,b))

32


In [101]:
print(np.sum(c))

21


In [102]:
#statastical functions

In [105]:
print(np.mean(c))
print(np.median(c))
print(np.min(c))
print(np.std(c))
print(np.max(c))

3.5
3.5
1
1.707825127659933
6


In [108]:
print(np.square(a))
print(np.sqrt(b))

[1 4 9]
[2.         2.23606798 2.44948974]


In [109]:
#broadcasting

In [111]:
c = np.array([[1, 2, 3], [4,5,6]])
d = np.array([10, 20, 30])
print(c+d)

[[11 22 33]
 [14 25 36]]


In [112]:
#handling with nan and infinite

In [113]:
a = np.array([1,2,3, np.nan, 4, np.inf])
print(a)

[ 1.  2.  3. nan  4. inf]


In [114]:
print(np.isnan(a))

[False False False  True False False]


In [115]:
print(np.nan_to_num(a))

[1.00000000e+000 2.00000000e+000 3.00000000e+000 0.00000000e+000
 4.00000000e+000 1.79769313e+308]


In [3]:
sales = np.array([2000, 4500, 3000, 8000])
high_sales = sales[sales > 4000]
print(high_sales)


[4500 8000]


In [5]:
#boolean indexing
sample = np.random.choice([0, 1], size=100, p=[0.7, 0.3])
print(sample)

[0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 0 1 1 0 0 0 0 0 1 1
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 1
 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 1]
